AWSTemplateFormatVersion: '2010-09-09'
Description: Stack que crea un bucket S3 privado con encriptación.

Resources:
  MyS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: my-secure-bucket-12345  # Cambia esto por un nombre único
      AccessControl: Private
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256

Outputs:
  BucketName:
    Description: Nombre del bucket S3
    Value: !Ref MyS3Bucket
