Mappings:
  RegionMap:
    us-east-1:
      AMI: "ami-123456"
    eu-west-1:
      AMI: "ami-987654"
    us-west-2:
      AMI: "ami-abcdef123456"

Resources:
  MyInstance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: t2.micro
      ImageId: !FindInMap [RegionMap, !Ref AWS::Region, AMI] 
