AWSTemplateFormatVersion: "2010-09-09"
Transform: ReplaceVariablesMacro  # Sustituye {{ENV}} con "Producción"

Resources:
  MyQueue:
    Type: AWS::SQS::Queue
    Properties:
      Description: "Cola de mensajes para el entorno {{ENV}}"
